adding references to custom resources
aws-controllers-k8s/emrcontainers-controller pull request #18
Opened 2022-09-09 19:56 UTC by dalbhanj

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1472

Description of changes: Once we add resource reference, emr-containers jobruns can reference virtualcluster custom resources directly. This is more k8s friendly and avoids exporting and importing variables

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-09 20:01 UTC, A-Hilaly commented on helm/templates/cluster-role-controller.yaml
> -rules:
This is the cause of failing tests in https://github.com/aws-controllers-k8s/code-generator/pull/362 - investigating why this is happening. For now holding all the PRs using the latest version of code-generator

2022-09-09 20:05 UTC, RedbackThomson requested changes

2022-09-09 20:05 UTC, RedbackThomson commented on apis/v1alpha1/generator.yaml
> +      virtualClusterID:
This actually needs to match the [AWS SDK name](https://docs.aws.amazon.com/sdk-for-go/api/service/emrcontainers/#StartJobRunInput) - so `VirtualClusterId`

2022-09-09 20:05 UTC, RedbackThomson commented on apis/v1alpha1/generator.yaml
> +          path: Status.Id
And confusingly, this needs to match the [CRD path](https://github.com/aws-controllers-k8s/emrcontainers-controller/blob/main/apis/v1alpha1/virtual_cluster.go#L58). So `Status.ID`

2022-09-09 20:08 UTC, dalbhanj commented on apis/v1alpha1/generator.yaml
> +          path: Status.Id
fixed

2022-09-09 20:08 UTC, dalbhanj commented on apis/v1alpha1/generator.yaml
> +      virtualClusterID:
fixed

2022-09-12 14:53 UTC, A-Hilaly commented
/retest

2022-09-12 14:58 UTC, A-Hilaly commented
Hi @dalbhanj, you will need to publish `ack-test-emrcontainers-f020dcf6:latest` in the emrcontainers AWS testing account. Ideally provide a script or a makefile so anyone can reproduce tests on there accounts https://github.com/aws-controllers-k8s/lambda-controller/tree/main/test/e2e/resources/lambda_function

2022-09-12 20:02 UTC, dalbhanj commented
/retest

2022-09-12 20:48 UTC, A-Hilaly approved these changes
++ Thanks Peter!

2022-09-12 21:21 UTC, A-Hilaly commented
/lgtm

2022-09-12 21:22 UTC, merged