adding Configurationoverrides to Jobrun
aws-controllers-k8s/emrcontainers-controller pull request #21
Opened 2022-10-21 20:39 UTC by dalbhanj

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1445

Description of changes: adding Configurationoverrides which will bring full parity with JobRun API

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-21 20:50 UTC, RedbackThomson requested changes
Amazing job with this! This is exactly what I had envisioned and I think it's being done in a really safe way. I have left some comments inline for the delta work. 

Could we have a test to apply these and ensure that the custom delta code works, given the edgecases?

2022-10-21 20:50 UTC, RedbackThomson commented on pkg/resource/job_run/hooks.go
> +		panic(err)
Panic-ing seems risky. Since it would break reconciliation for all the other resources handled by this controller. I understand we don't return errors in this method, but maybe we could just force it to return a delta if we find an error?

2022-10-21 20:50 UTC, RedbackThomson commented on pkg/resource/job_run/hooks.go
> +		if ackcompare.HasNilDifference(aConfig.MonitoringConfiguration, bConfig.MonitoringConfiguration) {
This is the same as line 57? It should never occur? Is this meant to be `aConfig.MonitoringConfiguration.PersistentAppUI`?

2022-10-21 20:50 UTC, RedbackThomson commented on pkg/resource/job_run/hooks.go
> +				delta.Add("Spec.ConfigurationOverrides", aConfig.MonitoringConfiguration, bConfig.MonitoringConfiguration)
Since we are doing a fine-grained diff in this method, I think we should be more fine-grained about the delta we return. We can always do a `delta.DifferentAt("Spec.ConfigurationOverrides")` to detect any changes within `ConfigurationOverrides`. My suggestion for this line:
```
delta.Add("Spec.ConfigurationOverrides.PersistentAppUI", aConfig.MonitoringConfiguration.PersistentAppUI, bConfig.MonitoringConfiguration.PersistentAppUI)
```

Following that pattern for each of the nested structs within the config

2022-10-21 20:50 UTC, RedbackThomson commented on pkg/resource/job_run/hooks.go
> +		}
Sounds good. We can delete the alternative below.

2022-10-21 20:50 UTC, RedbackThomson commented on test/e2e/resources/job_run.yaml
> +      name: $VIRTUALCLUSTER_NAME
Looks like we're missing some test changes here to support this?

2022-10-21 21:01 UTC, RedbackThomson commented on pkg/resource/job_run/hooks.go
> +		panic(err)
Ok so yeah panicking is not really an option. I just did some brainstorming with Amine about this. We think it would be best to validate the user input in a hook before the create request. Something that just attempts to parse it from YAML to the Go type. If that fails, fail early with a terminal condition error. After that, it should be created as per usual. Then whatever we know is being returned by the server has to be valid, and we can essentially ignore these errors. (Maybe we still want to debug log it, just in case this ever changes)

2022-10-21 21:20 UTC, dalbhanj commented on pkg/resource/job_run/hooks.go
> +		panic(err)
Hi @RedbackThomson , we are doing sanity checks here in this [pre-create hook](https://github.com/aws-controllers-k8s/emrcontainers-controller/pull/21/files#diff-9baa4732154f72d148c3a43ded927cb11cd18611fe1f1a378d80aa91ccef5abf). Let me know if this is enough

2022-10-21 21:20 UTC, dalbhanj commented on pkg/resource/job_run/hooks.go
> +		}
fixed in next commit

2022-10-21 21:20 UTC, dalbhanj commented on pkg/resource/job_run/hooks.go
> +				delta.Add("Spec.ConfigurationOverrides", aConfig.MonitoringConfiguration, bConfig.MonitoringConfiguration)
fixed in next commit

2022-10-21 21:20 UTC, dalbhanj commented on pkg/resource/job_run/hooks.go
> +		if ackcompare.HasNilDifference(aConfig.MonitoringConfiguration, bConfig.MonitoringConfiguration) {
fixed in next commit

2022-10-21 21:25 UTC, dalbhanj commented on test/e2e/resources/job_run.yaml
> +      name: $VIRTUALCLUSTER_NAME
Thanks for the feedback. I created separate [issue](https://github.com/aws-controllers-k8s/community/issues/1516) to work on test cases. I don't want this to be a blocker for this PR merge bcoz they are cumbersome and takes too much time to validate each test cases

2022-10-25 13:36 UTC, dalbhanj commented
/retest

2022-10-25 16:36 UTC, dalbhanj commented on test/e2e/resources/job_run.yaml
> +      name: $VIRTUALCLUSTER_NAME
Added e2e tests in latest commit

2022-10-25 22:25 UTC, A-Hilaly commented on pkg/resource/job_run/delta.go
> +	}
This part of the code is not needed. You'll have to instruct the code generator to not generate this part of the code. e.g https://github.com/aws-controllers-k8s/lambda-controller/blob/main/generator.yaml#L38-L40

2022-10-26 13:43 UTC, dalbhanj commented on pkg/resource/job_run/delta.go
> +	}
removed in latest commit

2022-10-26 15:44 UTC, A-Hilaly commented
/approve
/lgtm

2022-10-26 15:45 UTC, merged