adding jobrun state
aws-controllers-k8s/emrcontainers-controller pull request #23
Opened 2022-11-09 23:10 UTC by dalbhanj

Issue #, if available: Adding jobrun state, refer this https://github.com/aws-controllers-k8s/community/issues/1489

Description of changes: Kubectl can show state changes of jobruns

```
$ kubectl get jobruns -w
NAME               JOB-ID                STATE
my-ack-jobrun-01   0000000312np262is2t   FAILED
my-ack-jobrun-02   0000000312nrulbojo3   COMPLETED
my-ack-jobrun-03   0000000312t1q0qonkc   COMPLETED
my-ack-jobrun-04   0000000312uesu2s8cu   COMPLETED
my-ack-jobrun-05   0000000312uhf8rs910   COMPLETED
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-09 23:23 UTC, A-Hilaly approved these changes
LGTM
+++

2022-11-09 23:49 UTC, A-Hilaly commented on pkg/resource/job_run/delta.go
> +	}
Need to investigate why is this generated again
/hold

2022-11-10 15:29 UTC, dalbhanj commented on pkg/resource/job_run/delta.go
> +	}
Looks like there is a bug in code-generator latest commit. Reverting to previous commit (2944c87) solves the issue

2022-11-10 17:04 UTC, A-Hilaly commented
@dalbhanj can you try regenerating with code-generator 5ee0ac052c54f008dff50f6f5ebb73f2cf3a0bd7 instead? looks like we lost few helm features in this PR.

2022-11-10 17:48 UTC, dalbhanj commented
> @dalbhanj can you try regenerating with code-generator 5ee0ac052c54f008dff50f6f5ebb73f2cf3a0bd7 instead? looks like we lost few helm features in this PR.

Done

2022-11-10 21:57 UTC, A-Hilaly commented on apis/v1alpha1/generator.yaml
>        configurationOverrides:
This should be "ConfigurationOverrides" that's why code generation didn't work properly earlier

2022-11-11 17:21 UTC, A-Hilaly requested changes

2022-11-11 17:21 UTC, A-Hilaly commented on apis/v1alpha1/generator.yaml
> -        template_path: hooks/configurationOverrides/sdk_read_one_pre_set_output.go.tpl
Please keep this `configurationOverrides` because that's the directory of the hooks

2022-11-11 17:52 UTC, dalbhanj commented on apis/v1alpha1/generator.yaml
> -        template_path: hooks/configurationOverrides/sdk_read_one_pre_set_output.go.tpl
changing path to configuration_overrides to keep it compatible with other repos.

2022-11-11 17:53 UTC, dalbhanj commented on apis/v1alpha1/generator.yaml
>        configurationOverrides:
Done

2022-11-11 17:53 UTC, A-Hilaly approved these changes
/lgtm

2022-11-11 19:26 UTC, A-Hilaly approved these changes
/lgtm
/unhold

2022-11-11 19:26 UTC, merged