Testing virtualcluster crd
aws-controllers-k8s/emrcontainers-controller pull request #4
Opened 2022-05-23 15:09 UTC by dalbhanj

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1267

Description of changes: Completed building and testing test infra scripts for e2e testing. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-23 15:37 UTC, jaypipes commented on test/e2e/__init__.py
> +def load_eks_resource(resource_name: str, additional_replacements: Dict[str, Any] = {}):
you can just change this function name to `load_resource` since it doesn't have to do with EKS.

2022-05-23 15:43 UTC, jaypipes commented on test/e2e/bootstrappable/emr_eks_cluster.py
> +        cluster_endpoint = cluster["cluster"]["endpoint"]
Did you want to wrap this in a try/except block? What about when the cluster doesn't (yet) exist by the time this code runs?

2022-05-23 15:49 UTC, jaypipes commented on test/e2e/bootstrappable/emr_eks_cluster.py
> +            core_v1.patch_namespaced_config_map(AWS_AUTH_CONFIG_MAP_NAME, AWS_AUTH_NAMESPACE, auth_patch)
This is fine I guess. We could have also just created a simple YAML manifest containing all the Role, RoleBinding and ConfigMap stuff and `kubectl apply`'d it.

2022-05-23 17:25 UTC, RedbackThomson commented on test/e2e/bootstrappable/emr_eks_cluster.py
> +        cluster_endpoint = cluster["cluster"]["endpoint"]
We call `super().bootstrap()` above this block - which ensures the subresources are successfully created before continuing. Part of the EKS cluster bootstrap resource has waiters for the cluster and then for the nodegroup to become active.

2022-05-23 17:25 UTC, RedbackThomson commented on test/e2e/bootstrappable/emr_eks_cluster.py
> +            core_v1.patch_namespaced_config_map(AWS_AUTH_CONFIG_MAP_NAME, AWS_AUTH_NAMESPACE, auth_patch)
We have to call patch on the `aws-auth` ConfigMap, or we'll lock ourselves out. For the others, we could have manually applied it, sure.

2022-05-23 17:25 UTC, RedbackThomson commented on test/e2e/conftest.py
> +    return boto3.client('eks')
Not necessary for these tests. Please delete

2022-05-23 17:25 UTC, RedbackThomson commented on test/e2e/tests/test_virtualcluster.py
> +        assert cr
I don't see any tests here?

2022-05-23 18:41 UTC, dalbhanj commented on test/e2e/bootstrappable/emr_eks_cluster.py
> +        cluster_endpoint = cluster["cluster"]["endpoint"]
@jaypipes, please review @RedbackThomson response. Just let me know if I need to add try/except. Thanks!

2022-05-23 18:41 UTC, dalbhanj commented on test/e2e/__init__.py
> +def load_eks_resource(resource_name: str, additional_replacements: Dict[str, Any] = {}):
done

2022-05-23 18:42 UTC, dalbhanj commented on test/e2e/conftest.py
> +    return boto3.client('eks')
done

2022-05-23 18:42 UTC, dalbhanj commented on test/e2e/tests/test_virtualcluster.py
> +        assert cr
done.

2022-05-23 18:53 UTC, jaypipes commented on test/e2e/bootstrappable/emr_eks_cluster.py
> +        cluster_endpoint = cluster["cluster"]["endpoint"]
@dalbhanj no, it's all good. @RedbackThomson's comment explained this fully, thanks.

2022-05-26 22:18 UTC, RedbackThomson commented
/approve

2022-05-26 22:19 UTC, RedbackThomson commented
/retest

2022-05-26 22:19 UTC, RedbackThomson commented
/test all

2022-05-26 22:21 UTC, RedbackThomson commented
/test all

2022-05-27 15:17 UTC, jaypipes requested changes
one teeny thing with the go.local.mod file, @dalbhanj otherwise looks great. fix that up and I will squash-merge this one.

2022-05-27 16:51 UTC, RedbackThomson commented
/lgtm

2022-05-27 16:52 UTC, merged